[package]
name = "ibeam"
version = "0.1.0"
authors = ["git314 <git314@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.14.1"
tabwriter = "1.2.1"
owo-colors = "1.3.0"
pad = "0.1"
